#ifndef MAPPDEFINES
#define MAPPDEFINES


#define SD_CARD_FILE_PATH   "/media/media/mmcblk0p1/"

#define FILE_TYPE_32550_OS_SUFFIX  "bin"
#define FILE_TYPE_FIRMWARE_SUFFIX   "imx"
#define FILE_TYPE_SYSTEM_LIB_SUFFIX  "so";
#define FILE_TYPE_KERNEL_PREFIX   "zImage"
#define FILE_TYPE_BOOT_PREFIX   "u-boot"
#define FILE_TYPE_MASTER_APP_PREFIX   "MasterApp"

#define  FILE_TYPE_BOOT  1
#define FILE_TYPE_KERNEL  2
#define FILE_TYPE_32550_OS  3
#define FILE_TYPE_SYSTEM_LIB  4
#define FILE_TYPE_MASTER_APP  5
#define FILE_TYPE_SUB_APP 6

#define SUB_APP_MAX_NUMS  24
#define SUB_APP_NAME_LEN  32

#define TERM_TYPE_MF2352  0x00
#define TERM_TYPE_TRSM  0x01

#define CA_TYPE_VENDOR  0x00
#define CA_TYPE_ACQUIRE  0x01

#define FUNC_TYPE_SIGN_FIRMWARE  0x00
#define FUNC_TYPE_SIGN_APP  0x01
#define FUNC_TYPE_TEST_OP 0x02
#define FUNC_TYPE_DOWNLOAD_MK  0x03
#define FUNC_TYPE_DOWNLOAD_ACQUIRECA 0x04

#define DOWNLOAD_KEYS_TIME_OUT  2*60*1000

#define APP_PERM_FILE_LEN 1024*6
#define APP_PERM_ITEM_LEN  37
#define APP_PERM_PKG_NAME_LEN  32
#define APP_PERM_ITEM_FLAG_POS  32
#define  APP_PERM_ITEM_DELETE_FLAG 0x00
#define  APP_PERM_ITEM_NORMAL_FLAG  0x01

#define APP_PERM_BYTE_LEN 4
#define SIGN_DATA_BYTE_LEN  288
#define APP_SIGN_DATA_LEN  292

#endif // MAPPDEFINES

